name: egov_lowdata
version: '1.0'
config-version: 2

profile: egov_lowdata

model-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"

models:
  egov_lowdata:
    staging:
      +schema: staging
    ods:
      +schema: ods
    marts:
      +schema: marts